/* 複数のキャラクターのプロフィールを管理する */

export const characterProfiles = [
  {
    name: "桃瀬ひより",
    age: "14",
    firstPerson: "私",
    bloodType: "A",
    birthDate: "9月18日",
    favoriteFood: "プチトマト",
    club: "園芸部",
    hobbies: "家庭菜園",
    height: "145cm",
    description: "癒し系妹キャラやってます!!",
    imageUrl: "character/hiyori/p-hiyori.png",
    bgColor: "bg-yellow-100",
  },
  {
    name: "虹色まお",
    age: "18",
    firstPerson: "私",
    bloodType: "不明",
    birthDate: "不名",
    favoriteFood: "うざぎ、楽しいこと",
    club: "なし",
    hobbies: "魔法を試すこと",
    height: "149cm",
    description: "おばあちゃんっ子でお絵描きが大好きな魔法使いのたまご",
    imageUrl: "character/mao/p-mao.png",
    bgColor: "bg-orange-100",
  },
  {
    name: "名執 尽",
    age: "不明",
    FirstPerson: "私",
    Bloodtype: "不明",
    birthDate: "不名",
    favoriteFood: "不明",
    club: "なし",
    hobbies: "不明",
    height: "不明",
    description:
      "ダークパープルの燕尾服風スーツを纏った、優雅で洗練された姿をしている",
    imageUrl: "character/natori/p-natori.png",
    bgColor: "bg-sky-300",
  },
];
