version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - faster_whisper:/models
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
    tty: true
    env_file:
      - .env  # .envファイルを読み込む

volumes:
  faster_whisper:
