blank_issues_enabled: true
contact_links:
  - name: バグ報告
    url: https://github.com/your-repo/issues/new?template=bug_report.md
    about: バグを報告するためのテンプレート
  - name: 機能リクエスト
    url: https://github.com/your-repo/issues/new?template=feature_request.md
    about: 新しい機能をリクエストするためのテンプレート
  - name: リファクタリングリクエスト
    url: https://github.com/your-repo/issues/new?template=refactor-request.md
    about: リファクタリングをリクエストするためのテンプレート
